- name: 'Sandstorm Two Factor Authentication'
  uriPattern: 'neos/second-factor-login'
  httpMethods: ['GET']
  defaults:
    '@package': 'Sandstorm.NeosTwoFactorAuthentication'
    '@controller': 'Login'
    '@action': 'askForSecondFactor'
    '@format': 'html'
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - Validation'
  uriPattern: 'neos/second-factor-login'
  httpMethods: ['POST']
  defaults:
    '@package': 'Sandstorm.NeosTwoFactorAuthentication'
    '@controller': 'Login'
    '@action': 'checkSecondFactor'
    '@format': 'html'
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - Setup'
  uriPattern: 'neos/second-factor-setup'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'setupSecondFactor'
      '@format': 'html'
  httpMethods: ['GET']
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - Create 2FA'
  uriPattern: 'neos/second-factor-setup'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'createSecondFactor'
      '@format': 'html'
  httpMethods: ['POST']

- name: 'Sandstorm Two Factor Authentication - Setup TOTP'
  uriPattern: 'neos/second-factor-setup/totp'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'setupTotp'
      '@format': 'html'
  httpMethods: ['GET']
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - Setup WebAuthn'
  uriPattern: 'neos/second-factor-setup/webauthn'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'setupWebAuthn'
      '@format': 'html'
  httpMethods: ['GET']
  appendExceedingArguments: true

- name: 'Sandstorm Two Factor Authentication - WebAuthn register options'
  uriPattern: 'neos/second-factor-webauthn/register-options'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'webAuthnRegisterOptions'
      '@format': 'json'
  httpMethods: ['POST']

- name: 'Sandstorm Two Factor Authentication - WebAuthn register verify'
  uriPattern: 'neos/second-factor-webauthn/register-verify'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'webAuthnRegisterVerify'
      '@format': 'json'
  httpMethods: ['POST']

- name: 'Sandstorm Two Factor Authentication - WebAuthn authenticate options'
  uriPattern: 'neos/second-factor-webauthn/authenticate-options'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'webAuthnAuthenticateOptions'
      '@format': 'json'
  httpMethods: ['POST']

- name: 'Sandstorm Two Factor Authentication - WebAuthn authenticate verify'
  uriPattern: 'neos/second-factor-webauthn/authenticate-verify'
  defaults:
      '@package': 'Sandstorm.NeosTwoFactorAuthentication'
      '@controller': 'Login'
      '@action': 'webAuthnAuthenticateVerify'
      '@format': 'json'
  httpMethods: ['POST']
